server:
  port: 9901
  servlet:
    context-path: /standlone

swagger:
  rest:
    package: org.framework.hsven.demo.db

spring:
  application: demo-db-single-app
  messages:
    basename: i18n/messages
  datasource:
    url: jdbc:mysql://192.168.1.21:3306/irdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: irsoft
    password: irsoft
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 20
    max-wait: 10000
    min-idle: 3
    initial-size: 5
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 18800
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=50)
    type: com.alibaba.druid.pool.DruidDataSource
