#dm
spring.datasource.driver-class-name=dm.jdbc.driver.DmDriver
spring.datasource.url=jdbc:dm://192.168.1.33:5236/irdb
spring.datasource.username=irdb
spring.datasource.password=Hthy_1607
#extend properties
extend.table.useActualColumnNames=false
